#!/usr/bin/python
# -*- coding: utf-8 -*-

# With the MindfulClock you turn your device into a Bell of Mindfulness.
# Concept, Design: Marcurs Möller
#                  <marcus.moeller@outlook.com>
#                  <http://apps.microsoft.com/windows/de-de/app/
#                   mindfulclock/58063160-9cc6-4dee-9d92-17df4ce4318a>
# Programming: Andreas Ulrich
#              <ulrich3110@gmail.com>,
#              <http://erasand.jimdo.com/kontakt/>
#
# This file is part of the "MindfulClock".
# "MindfulClock" is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# "MindfulClock" is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details. You should
# have received a copy of the GNU General Public License along with
# "MindfulClock".  If not, see <http://www.gnu.org/licenses/>.


import sys
import wx
import mfc1


'''The start command for the sourcecode distribution.
   mfc1dist [OPTIONS]
     --start-minim: Start the clock minimized.
     --tb-icon: Use instead of the application indicator the classic
                system tray.
     --help: Show this help.

'''


if __name__ == '__main__':
    # Command line options
    clio = sys.argv
    if '--start-minim' in clio:
        mini = True
    else:
        mini = False
    if '--tb-icon' in clio:
        tbar = True
    else:
        tbar = False
    if '--help' in clio:
        print('')
        print('Source code distribution of the MindFulClock.')
        print('Commando: mfc1dist [OPTIONS]')
        print('')
        print('  --start-minim   Start the clock minimized.')
        print('')
        print('  --tb-icon       Use instead of the application')
        print('                  indicator the classic system tray.')
        print('')
        print('  --help          Show this help.')
        print('')
    else:
        app = wx.App()
        frame = mfc1.GUI(systray=mini, tbicon=tbar)
        app.MainLoop()
